# Generated by Django 3.2 on 2022-12-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveVel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lAxisNo', models.IntegerField()),
                ('dVel', models.FloatField()),
                ('dAccel', models.FloatField()),
                ('dDecel', models.FloatField()),
            ],
        ),
    ]
